name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# evita dois deploys concorrentes para o mesmo ambiente
concurrency:
  group: prod-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production   # usa o ambiente “production” do GitHub (opcional, mas recomendado)
    steps:
      - name: Checkout (full history p/ métricas)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # importante para ferramentas que calculam lead time (histórico completo)

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # ajuste a versão do seu projeto

      # --- RESTORE ---
      - name: Restore
        run: dotnet restore ./SeuProjeto.sln   # ou ./src/SeuProjeto.csproj

      # --- BUILD ---
      - name: Build (Release)
        run: dotnet build ./SeuProjeto.sln --configuration Release --no-restore
        # se preferir, pode apontar para o .csproj específico em vez do .sln

      # --- TEST ---
      - name: Test
        run: dotnet test ./tests/SeuProjeto.Tests.csproj --configuration Release --no-build --verbosity normal
        # ajuste o caminho para o projeto de testes

      # --- DEPLOY (script próprio) ---
      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Deploy
        id: deploy
        run: ./deploy.sh

      # --- OPÇÃO: DEPLOY AZURE (se for usar WebApp) ---
      # - name: Publish
      #   run: dotnet publish ./src/SeuProjeto.csproj -c Release -o ./out
      # - name: Deploy to Azure WebApp
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: SEU_WEBAPP
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: ./out

      # --- SLEUTH NOTIFY ---
      - name: Notify Sleuth
        if: ${{ success() && steps.deploy.outcome == 'success' }}
        uses: sleuth-io/sleuth-action@main   # não existe v1, use main ou SHA
        with:
          api_key: ${{ secrets.SLEUTH_API_KEY }}
          environment: production
          revision: ${{ github.sha }}
          repo: ${{ github.repository }}
          deployed_at: ${{ github.event.head_commit.timestamp }}
